stages:
  - deps
  - test
  - build
  - package

variables:
  CONTAINER_NAME: thethingsnetwork/ttn

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - vendor/

before_script:
  - rm -rf $GOPATH/src
  - mkdir -p $GOPATH/src/github.com/TheThingsNetwork/ttn
  - cp -R . $GOPATH/src/github.com/TheThingsNetwork/ttn

deps:
  stage: deps
  image: golang:latest
  script:
    - pushd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - make deps
    - popd
    - cp -R $GOPATH/src/github.com/TheThingsNetwork/ttn/vendor/* vendor/

tests:
  stage: test
  image: golang:latest
  services:
    - ansi/mosquitto
    - redis
  variables:
    REDIS_HOST: redis
    MQTT_HOST: ansi-mosquitto
  script:
    - pushd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - make deps
    - make test
    - popd

binaries:
  stage: build
  image: golang:latest
  script:
    - mkdir release
    - export CI_BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    - echo "date $CI_BUILD_DATE" >> release/info
    - echo "commit $CI_BUILD_REF" >> release/info
    - pushd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - make deps
    - GOOS=linux GOARCH=386 make build
    - GOOS=linux GOARCH=amd64 make build
    - GOOS=linux GOARCH=arm make build
    - GOOS=darwin GOARCH=amd64 make build
    - GOOS=windows GOARCH=386 make build
    - GOOS=windows GOARCH=amd64 make build
    - popd
    - cp -R $GOPATH/src/github.com/TheThingsNetwork/ttn/release/* release/
  artifacts:
    paths:
      - release/

gitlab-image:
  stage: package
  image: docker:git
  services:
    - "docker:dind"
  script:
    - cd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - docker build -t ttn .
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" registry.gitlab.com
    - docker tag ttn registry.gitlab.com/$CONTAINER_NAME:$CI_BUILD_REF_NAME
    - docker push registry.gitlab.com/$CONTAINER_NAME:$CI_BUILD_REF_NAME

dockerhub-image:
  only:
    - master@thethingsnetwork/ttn
    - refactor@thethingsnetwork/ttn
  stage: package
  image: docker:git
  services:
    - "docker:dind"
  script:
    - cd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - docker build -t ttn .
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
    - docker tag ttn $CONTAINER_NAME:$CI_BUILD_REF_NAME
    - docker push $CONTAINER_NAME:$CI_BUILD_REF_NAME

azure-binaries:
  only:
    - master@thethingsnetwork/ttn
    - refactor@thethingsnetwork/ttn
  stage: package
  image: registry.gitlab.com/thethingsindustries/upload
  script:
    - cd release
    - export STORAGE_CONTAINER=release STORAGE_KEY=$AZURE_STORAGE_KEY ZIP=true TGZ=true PREFIX=$CI_BUILD_REF_NAME/
    - upload *
