stages:
  - deps
  - test
  - build
  - package

variables:
  CONTAINER_NAME: thethingsnetwork/ttn

cache:
    key: "$CI_BUILD_REF_NAME/go_src"
    paths:
      - go_src/
      - vendor/

before_script:
  - git submodule update --init
  - rm -rf $GOPATH/src
  - "if [ -d go_src ]; then mv go_src $GOPATH/src; fi"
  - mkdir -p $GOPATH/src/github.com/TheThingsNetwork/ttn
  - cp -R . $GOPATH/src/github.com/TheThingsNetwork/ttn

after_script:
  - rm -rf $GOPATH/src/github.com/TheThingsNetwork/ttn
  - cp -R $GOPATH/src go_src

deps:
  stage: deps
  image: golang:latest
  script:
    - pushd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - TARGET_PLATFORM=linux-386 make deps
    - TARGET_PLATFORM=linux-amd64 make deps
    - TARGET_PLATFORM=linux-arm make deps
    - TARGET_PLATFORM=darwin-amd64 make deps
    - TARGET_PLATFORM=windows-386 make deps
    - TARGET_PLATFORM=windows-amd64 make deps
    - make test-deps cover-deps
    - popd

tests:
  stage: test
  image: golang:latest
  services:
    - ansi/mosquitto
    - redis
  variables:
    REDIS_HOST: redis
    MQTT_HOST: ansi-mosquitto
  script:
    - pushd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - make test
    - popd

binaries:
  stage: build
  image: golang:latest
  script:
    - pushd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - TARGET_PLATFORM=linux-386 make build
    - TARGET_PLATFORM=linux-amd64 make build
    - TARGET_PLATFORM=linux-arm make build
    - TARGET_PLATFORM=darwin-amd64 make build
    - TARGET_PLATFORM=windows-386 make build
    - TARGET_PLATFORM=windows-amd64 make build
    - popd
    - mkdir release
    - cp -R $GOPATH/src/github.com/TheThingsNetwork/ttn/release/* release/
  artifacts:
    paths:
      - release/

container:
  stage: package
  image: docker:git
  services:
    - "docker:dind"
  script:
    - cd $GOPATH/src/github.com/TheThingsNetwork/ttn
    - docker build -t ttn .
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" registry.gitlab.com
    - docker tag ttn registry.gitlab.com/$CONTAINER_NAME:$CI_BUILD_REF_NAME
    - docker push registry.gitlab.com/$CONTAINER_NAME:$CI_BUILD_REF_NAME
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
    - docker tag ttn $CONTAINER_NAME:$CI_BUILD_REF_NAME
    - docker push $CONTAINER_NAME:$CI_BUILD_REF_NAME
