language: go

go:
  - 1.5

install:
    - go get $(comm -23 <(sort <(go list -f '{{join .Deps "\n"}}' ./...) | uniq) <(go list std) | grep -v TheThingsNetwork)
script:
  - go list ./... | grep -v integration | xargs go test
  - sh -c 'FMTRES="$(go fmt ./...)"; if [ ! -z "$FMTRES" ]; then echo $FMTRES; exit 255; fi'
  - go vet ./...
