debug: true
discovery-server: "localhost:1900"
auth-servers:
  ttn-account: "https://account.thethingsnetwork.org"
  ttn-account-preview: "https://preview.account.thethingsnetwork.org"
  ttn-account-staging: "https://preview.account.thethingsnetwork.org"
tls: true
key-dir: "./.env/networkserver/"
noc-server: noc.thethingsnetwork.org:1905
